---
name: Jupyter
category: Interactive Apps
subcategory: Servers
role: batch_connect
description: |
  This app will launch a [Jupyter] server on a cluster running [Apptainer]

  [Jupyter]: https://jupyter.org/
  [Apptainer]: https://apptainer.org/
